apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: awesome-media-backend-deployment
  labels:
    app: awesome-media-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: awesome-media-backend
  template:
    metadata:
      labels:
        app: awesome-media-backend
    spec:
      containers:
      - name: awesome-media-backend
        image: icp.ghama.io:8500/skhy-user1/awesome-media-backend:1.0
        ports:
        - containerPort: 8090
        imagePullPolicy: Always
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: k8s
        - name: MYSQL_DATABASE
          value: db_example
        - name: MYSQL_PASSWORD
          value: ThePassword     
        - name: MYSQL_USER
          value: springuser
        resources:
          requests:
            memory: "256Mi"
            cpu: "0.5"
          limits:
            memory: "1Gi" 
            cpu: "1"
