apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: awesome-media-backend-hpa
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    kind: Deployment
    name: awesome-media-backend-deployment
  targetCPUUtilizationPercentage: 50